name: Jira → In Review when Copilot’s 2nd commit lands

on:
  pull_request:
    types: [synchronize]

permissions:
  contents: read
  pull-requests: read

jobs:
  mark_in_review:
    # Adjust the author/label checks to your setup if needed
    if: github.event.pull_request.commits >= 2
    runs-on: ubuntu-latest
    steps:
      - name: Get Jira key from PR title
        id: key
        shell: bash
        run: |
          set -euo pipefail
          title="${{ github.event.pull_request.title }}"

          # Match ABC-123 style key in title only
          if [[ "$title" =~ ([A-Z][A-Z0-9]+-[0-9]+) ]]; then
            echo "key=${BASH_REMATCH[1]}" >> "$GITHUB_OUTPUT"
          else
            echo "No Jira issue key found in PR title" >&2
            exit 1
          fi

      - name: Call Jira Automation webhook
        env:
          WEBHOOK_URL: ${{ secrets.JIRA_WEBHOOK_URL }}
          WEBHOOK_TOKEN: ${{ secrets.JIRA_WEBHOOK_TOKEN }}
          ISSUE_KEY: ${{ steps.key.outputs.key }}
        run: |
          set -euo pipefail

          # Single work item in the URL as ?issue=KEY (per Jira spec)
          curl -sS -X POST \
            -H "Content-Type: application/json" \
            -H "X-Automation-Webhook-Token: ${WEBHOOK_TOKEN}" \
            "${WEBHOOK_URL}?issue=${ISSUE_KEY}"
